---
printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: "all"
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: "avoid"
requirePragma: false
insertPragma: false
proseWrap: "preserve"
